In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
x = [1, 2, 3, 4, 5]
print(type(x))
print("----------------------------------------------------------------")
s = np.array(5)
print(s.ndim)
print("----------------------------------------------------------------")
y = np.array([1, 2, 3, 4, 5,6])
print(y)
print("----------------------------------------------------------------")
m = np.array([[1, 2, 3],
                [4, 5, 6],
                 [7, 8, 9]])
m
print(m.ndim)
print(m.shape)

<class 'list'>
----------------------------------------------------------------
0
----------------------------------------------------------------
[1 2 3 4 5 6]
----------------------------------------------------------------
2
(3, 3)


In [9]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat
print(mat.shape[0])

3


In [ ]:
vec = np.array([1,2,3,4])
mat = vec.reshape((vec.shape[0]))
print(mat)

[1 2 3 4]


In [11]:
def array_reshape(arr : list ,rows : int, cols : int):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except(TypeError,ValueError) as e:
        raise ValueError(f"Invalid reshape:{e}")


In [14]:
vec = [1,2,3,4,5,6]
array_reshape(vec,2,3)


array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(m.dtype)
print('=====================')
fmat = m.astype('float')
print(fmat)
print(fmat.dtype)


int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


In [31]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

v = np.array([3,4,5])
print(m[1,2])

m[1:3, 0:2]

6


array([[4, 5],
       [7, 8]])

In [32]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
matT = mat.T
matT

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])