Part 1: Smart Array Factory

In [2]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == 'zeros':
        return np.zeros(shape)
    
    elif mode == 'ones':
        return np.ones(shape)
    
    elif mode == 'full':
        if value is None:
            raise ValueError("Value must be provided when mode is 'full'")
        return np.full(shape, value)
    
    elif mode == 'identity':
       
        size = shape if isinstance(shape, int) else shape[0]
        return np.identity(size)
    
    else:
        raise ValueError(f"Unsupported mode: '{mode}'. Choose from 'zeros', 'ones', 'full', 'identity'.")



print("Zeros Array:\n", array_factory('zeros', (2, 3)))
print("\nOnes Array:\n", array_factory('ones', (2, 2)))
print("\nFull Array:\n", array_factory('full', (3, 4), value=5))
print("\nIdentity Matrix:\n", array_factory('identity', 3))

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1.]
 [1. 1.]]

Full Array:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Part 2: The secure_reshape_and_stack Function

In [3]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # 1. Convert inputs to ndarray
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # 2. Rule: Change the shape of arr1 to new_shape
        reshaped_arr1 = arr1.reshape(new_shape)

        # 3. Rule: Vertical Stacking (vstack)
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except (ValueError, TypeError) as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")


d1 = [1, 2, 3, 4, 5, 6]
d2 = [[7, 8, 9], [10, 11, 12]]

result = secure_reshape_and_stack(d1, d2, (2, 3))
print("Combined Dataset:\n", result)


Combined Dataset:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
